#!/bin/bash

# Playbook to be run
PLAYBOOK=$1

# Check whether a command exists - returns 0 if it does, 1 if it does not
function exists {
  if command -v $1 >/dev/null 2>&1
  then
    return 0
  else
    return 1
  fi
}

# Install Ansible if necessary
if ! exists pip; then
    echo "Install pip"
    sudo easy_install --quiet pip
else
	echo "pip installed."
fi

# Install pip if necesary
if ! exists ansible; then
    echo "Install ansible"
    sudo pip install -q ansible
else
	echo "ansible installed."
fi

# Install virtualenv if necesary
if ! exists virtualenv; then
    echo "Install virtualenv"
    sudo pip install -q virtualenv
else
	echo "virtualenv installed."
fi

if [ -z "$PLAYBOOK" ]; then
	echo "No playbook specified. Create a playbook for each computer you need to configure."
else	
	echo "Running the primary ansible playbook"
	ansible-playbook --ask-become-pass $PLAYBOOK
fi
